# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/test/bin_input_disp_FPGA/bin_input_disp_FPGA.cache/wt [current_project]
set_property parent.project_path D:/test/bin_input_disp_FPGA/bin_input_disp_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/test/bin_input_disp_FPGA/bin_input_disp_FPGA.srcs/sources_1/new/bin_in_disp_FPGA.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/test/bin_input_disp_FPGA/bin_input_disp_FPGA.srcs/constrs_1/new/bin_in_disp_FPGA.xdc
set_property used_in_implementation false [get_files D:/test/bin_input_disp_FPGA/bin_input_disp_FPGA.srcs/constrs_1/new/bin_in_disp_FPGA.xdc]


synth_design -top top_module -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_module.dcp

catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
